# Generated by Django 5.1.1 on 2024-10-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_contact_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.CharField(default=1, max_length=300, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone_Number',
            field=models.IntegerField(default=1, max_length=10, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
